%YAML:1.0

# ============================================================================
# ORB-SLAM3 Baseline — EuRoC MAV (Stereo, no semantic)
# ============================================================================
Camera.type: "PinHole"

Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

Camera.k1: -0.28340811
Camera.k2: 0.07395907
Camera.p1: 0.00019359
Camera.p2: 0.00001762

Camera.k3: 0.0

Camera.width: 752
Camera.height: 480

Camera.fps: 20.0
Camera.bf: 47.90639384423901
Camera.RGB: 1

ThDepth: 35.0

ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

IMU: 0

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
